- name: Agent {{ agent_index }}-- Ensure "{{ teamcity_agent_install_dir }}/agent{{ agent_index }}" exists
  file:
    path: "{{ teamcity_agent_install_dir }}/agent{{ agent_index }}"
    state: directory
    recurse: yes

- name: Agent {{ agent_index }}-- Extract buildAgent.zip
  unarchive:
    src: /tmp/buildAgent.zip
    dest: "{{ teamcity_agent_install_dir }}/agent{{ agent_index }}"
    creates: "{{ teamcity_agent_install_dir }}}/agent{{ agent_index }}/bin/agent.sh"
    remote_src: yes

- name: Agent {{ agent_index }}-- Copy agent configuration
  template:
    src: "buildAgent.properties.j2"
    dest: "{{ teamcity_agent_install_dir }}/agent{{ agent_index }}/conf/buildAgent.properties"

- name: Agent {{ agent_index }}-- Change ownership of all Build Agent files to "{{ teamcity_agent_account }}"
  file:
    path: "{{ teamcity_agent_install_dir }}/agent{{ agent_index }}"
    owner: "{{ teamcity_agent_account }}"
    recurse: yes

- name: Agent {{ agent_index }}-- Deploy TeamCity systemd unit
  template:
    src: "teamcity-agent.service.j2"
    dest: "/etc/systemd/system/teamcity-agent{{ agent_index }}.service"
  become: yes
  notify: reload_agents
