- name: Make sure directory "{{ hostvars.localhost.teamcity_dest }}/agentXX" exists
  file:
    path: "{{ hostvars.localhost.teamcity_dest }}/agent{{ agent_index }}"
    state: directory
    recurse: yes

- name: Extract buildAgent.zip
  unarchive:
    src: /tmp/buildAgent.zip
    dest: "{{ hostvars.localhost.teamcity_dest }}/agent{{ agent_index }}"
    creates: "{{ hostvars.localhost.teamcity_dest }}/agent{{ item }}/bin/agent.sh"
    remote_src: yes

- name: Rename Buildagent buildAgent.dist.properties
  copy:
    src: "{{ hostvars.localhost.teamcity_dest }}/agent{{ agent_index }}/conf/buildAgent.dist.properties"
    dest: "{{ hostvars.localhost.teamcity_dest }}/agent{{ agent_index }}/conf/buildAgent.properties"
    remote_src: yes
    force: no

- lineinfile:
    path: "{{ hostvars.localhost.teamcity_dest }}/agent{{ agent_index }}/conf/buildAgent.properties"
    regexp: "{{ inner_item.regexp }}"
    line: "{{ inner_item.line }}"
  loop:
    - { regexp: "^serverUrl=http://localhost:8111/", line: "serverUrl=http://{{ hostvars.localhost.teamcity_server }}:8111/" }
    - { regexp: "^name=", line: "name={{ build_hostname }}" }
  loop_control:
    loop_var: inner_item

- name: Change ownership of all Build Agent files to "{{ teamcity_agent_account }}"
  file:
    path: "{{ hostvars.localhost.teamcity_dest }}/agent{{ agent_index }}"
    owner: "{{ teamcity_agent_account }}"
    group: programmers
    recurse: yes
