---
- name: Install required packages
  yum: 
    name:
      - xorg-x11-drv-dummy # Used to allow tests that require GUI
    state: latest
    use_backend: yum
  become: yes

- name: Install Java
  include_role:
    name: lean_delivery.java
  
- name: Get the VM Hostname
  shell: hostname
  register: hostname_result

- name: Download Agent zip
  get_url:
    url: "{{ teamcity_server_url }}/update/buildAgent.zip"
    dest: /tmp/buildAgent.zip
    mode: 0775
  register: get_url_result

- name: Install Build Agents
  include_role:
    name: build_agent
  vars:
    agent_index: "{{ item }}"
    build_hostname: "{{ hostname_result.stdout }}"
  loop:
    - "01"
    - "02"
    - "03"
    - "04"
  when: get_url_result.changed == True

#- name: "Put TeamCity Agent service file (systemd)"
#  template:
#    src: "teamcity-agent.service.j2"
#    dest: "/lib/systemd/system/teamcity-agent.service"
#    #mode: 0644
#  when: "ansible_service_mgr == 'systemd'"
#- name: "Ensure TeamCity Agent is running"
#  service:
#    name: teamcity-agent
#    state: started
#    enabled: yes

- name: Automatic buildAgent Start - write init.d file
  template:
    src: teamcity.j2
    dest: /etc/init.d/teamcity
    mode: 0755
    force: no
  become: yes

- name: Automatic buildAgent Start - enable and start service
  service:
    name: teamcity
    enabled: yes
    state: started
  become: yes

- name: Create /home/{{ teamcity_agent_account }}/builds directory
  file:
    path: "/home/{{ teamcity_agent_account }}/builds/"
    state: directory
    owner: "{{ teamcity_agent_account }}"
    group: programmers

- name: Install autofs
  yum:
    name:
      - autofs
      - nfs-utils
    state: latest
    use_backend: yum
  become: yes
    
- name: Start the autofs service
  service:
    name: autofs
    enabled: yes
    state: started
  become: yes

- name: link /artefact to /net/unix-artefact/volume1/unix2/artefact
  file:
    src: /net/unix-artefact/volume1/unix2/artefact
    dest: /artefact
    owner: "{{ teamcity_agent_account }}"
    group: programmers
    state: link
  become: yes

- name: Write the Xdummy xorg.conf file
  copy:
    src: "{{ role_path }}/files/xorg.conf"
    dest: "/etc/X11/xdummy_xorg.conf"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Add cron job to start Xdummy on boot
  cron:
    name: "Start Xdummy"
    special_time: reboot
    job: "sleep 60 ; Xorg -noreset +extension GLX +extension RANDR +extension RENDER -config xdummy_xorg.conf :77 >/dev/null 2>&1"
    user: root
  register: xdummy_cron
  become: yes

# Ansible 2.7 includes a reboot module, move to that when possible. 
- name: Reboot immediately if there was a change.
  reboot:
  when: xdummy_cron is changed
