---
- name: Install required packages
  yum: 
    name:
      - xorg-x11-drv-dummy # Used to allow tests that require GUI
    state: latest
    use_backend: yum
  become: yes

- name: Install Java
  include_role:
    name: lean_delivery.java
  vars:
    java_distribution: adoptopenjdk
    java_major_version: 11

- name: Get the VM Hostname
  shell: hostname
  register: hostname_result

- name: Download Agent zip
  get_url:
    url: "{{ teamcity_server_url }}/update/buildAgent.zip"
    dest: /tmp/buildAgent.zip
    mode: 0775
  register: get_url_result

- name: Install Build Agents
  include_tasks:
    file: "build_agent.yml"
  vars:
    agent_index: "{{ '%02d' | format(agent_id) }}"
    build_hostname: "{{ hostname_result.stdout }}"
  loop: "{{ range(1, 4 + 1, 1) | list }}"
  loop_control:
    loop_var: agent_id

# - name: Automatic buildAgent Start - write init.d file
#   template:
#     src: teamcity.j2
#     dest: /etc/init.d/teamcity
#     mode: 0755
#     force: no
#   become: yes

# - name: Automatic buildAgent Start - enable and start service
#   service:
#     name: teamcity
#     enabled: yes
#     state: started
#   become: yes

- name: Create /home/{{ teamcity_agent_account }}/builds directory
  file:
    path: "/home/{{ teamcity_agent_account }}/builds/"
    state: directory
    owner: "{{ teamcity_agent_account }}"

