---
- name: Install Homebrew + OpenJDK
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_installed_packages:
      - "{{ java.openjdk[ansible_os_family] }}"
  when: not cpp_buildmachine

- name: Link "{{ java.openjdk[ansible_os_family] }}"
  community.general.homebrew:
    name: "{{ java.openjdk[ansible_os_family] }}"
    state: linked

- name: "Ensure {{ java.openjdk[ansible_os_family] }} is linked"
  ansible.builtin.command: ln -sfn $HOMEBREW_PREFIX/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
  become: true
  when: ansible_os_family == 'Darwin'

- name: Create teamcity agent install directory
  ansible.builtin.file:
    path: "{{ teamcity_agent_install_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ teamcity_build_username }}"

- name: Download Agent zip
  ansible.builtin.get_url:
    url: "{{ teamcity_buildagent_zip_url }}"
    dest: "{{ teamcity_downloaded_buildagent_zip }}"
    mode: 0775

- name: "Ensure LaunchDaemons directory exists"
  ansible.builtin.file:
    path: "/Library/LaunchDaemons"
    state: directory
    mode: 0755
    owner: "{{ teamcity_build_username }}"
  become: true

- name: Install Teamcity Agent
  ansible.builtin.include_tasks:
    file: install_agent.yml

- name: "Deploy TeamCity launchd service"
  ansible.builtin.template:
    src: jetbrains.teamcity.BuildAgent.plist.j2
    dest: "/Library/LaunchDaemons/jetbrains.teamcity.BuildAgent.{{ item.teamcity_agent_name }}.plist"
    mode: 0644
  register: teamcity_single_agent_launchd_service
  loop: "{{ teamcity_agents }}"
  become: true

- name: "Run TeamCity launchd service"  # noqa: no-changed-when
  ansible.builtin.command: launchctl load "/Library/LaunchDaemons/jetbrains.teamcity.BuildAgent.{{ item.teamcity_agent_name }}.plist"
  when: ansible_os_family == 'Darwin' and teamcity_single_agent_launchd_service.changed
  loop: "{{ teamcity_agents }}"
  become: true

- name: "Change ownership of all Build Agent files"
  ansible.builtin.file:
    path: "{{ teamcity_agent_install_dir }}/{{ item.teamcity_agent_name }}"
    owner: "{{ teamcity_build_username }}"
    recurse: true
  become: true
  loop: "{{ teamcity_agents }}"
