---

- name: Set up TeamCity agent
  include_tasks: "{{ item }}"
    with_first_found:
      - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
